version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/internal/integration"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
