name: Linux Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        go-version: 
          - "1.23"
          - "1.24"
          - "1.25"
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5.5.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Create a network namespace for unprivileged tests
        run: sudo ip netns add unpriv0

      - name: Run tests
        run: go test -v -race -tags gofuzz ./...
